RTC patches #2. This gets the RTC working with a fixed value. Set FORCE_RTC in op_init.c to try it out.
Todo:

1) sysctl for RTC, to set RTC value

2) setting of sysctl in op_start

3) Fill in opd_header sensibly

4) GUI - modprobe on start, list RTC event only, one counter

5) Documentation

6) little output things (e.g. don't print unit mask)

7) SMP ?? anything else ?

diff --git a/dae/op_start b/dae/op_start
--- a/dae/op_start
+++ b/dae/op_start
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id: op_start,v 1.56 2002/01/07 02:30:39 movement Exp $
+# $Id: op_start,v 1.57 2002/01/14 07:02:02 movement Exp $
 # COPYRIGHT (C) 2000 THE VICTORIA UNIVERSITY OF MANCHESTER and John Levon
 # This program is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the Free
@@ -104,6 +104,22 @@ do_help() {
 	  --help                       this message" >&2
 }
 
+load_module() {
+	grep oprof /proc/devices >/dev/null
+	if [ "$?" -ne 0 ]; then
+		modprobe oprofile
+		if [ "$?" != "0" ]; then
+			echo "Couldn't load oprofile.o module" >&2
+			exit 1
+		fi
+		grep oprofile /proc/modules >/dev/null
+		if [ "$?" != "0" ]; then
+			echo "Couldn't load oprofile.o module" >&2
+			exit 1
+		fi
+	fi
+} 
+
 # initialise parameters
 do_init() {
 	LOG_FILE=
@@ -124,7 +140,7 @@ do_init() {
 	PGRP_FILTER=0
 	VERBOSE=0
 
-	CPUTYPE=`op_help --get-cpu-type`
+	CPUTYPE=`cat /proc/sys/dev/oprofile/cpu_type`
 
 	case "$CPUTYPE" in
 		0|1|2)
@@ -134,6 +150,10 @@ do_init() {
 		3)
 			OP_MAX_COUNTERS=4
 			MAX_COUNTER=3
+			;;
+		4)
+			OP_MAX_COUNTERS=1
+			MAX_COUNTER=0
 			;;
 		*)
 			echo "Unknown cpu type \"$CPUTYPE\"" >&2
@@ -351,20 +371,6 @@ do_stop() {
 
 # setup and start module
 do_setup() {
-	grep oprof /proc/devices >/dev/null
-	if [ "$?" -ne 0 ]; then
-		modprobe oprofile expected_cpu_type=$CPUTYPE
-		if [ "$?" != "0" ]; then
-			echo "Couldn't load oprofile.o module" >&2
-			exit 1
-		fi
-		grep oprofile /proc/modules >/dev/null
-		if [ "$?" != "0" ]; then
-			echo "Couldn't load oprofile.o module" >&2
-			exit 1
-		fi
-	fi
-
 	if [ ! -d "$DIR" ]; then
 	       mkdir -p "$DIR"
 	       if [ "$?" != "0" ]; then
@@ -502,9 +508,14 @@ if [ "$UID" != "0" ]; then
 	exit 1
 fi
  
+load_module
 do_init
 do_options $@
 do_stop
 do_setup
-do_sysctl_setup
+# FIXME 
+echo $CPUTYPE
+if test "$CPUTYPE" != 4; then 
+   do_sysctl_setup
+fi
 do_start
