JIT support (for profiling Java applications) added

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -3,6 +3,7 @@ SUBDIRS = \
 	m4 \
 	libutil \
 	libop \
+	libopagent \
 	libdb \
 	libutil++ \
 	libopt++ \
@@ -11,10 +12,12 @@ SUBDIRS = \
 	utils \
 	libregex \
 	libpp \
+	opjitconv \
 	pp \
 	events \
 	doc \
-	gui
+	gui \
+	agents
 
 ACLOCAL_AMFLAGS = -I m4
 
@@ -38,11 +41,27 @@ install-exec-local:
 	-mkdir -p $(MODINSTALLDIR)/oprofile
 	cp module/oprofile-module.o $(MODINSTALLDIR)/oprofile/oprofile.o
 	if test $(KVERS) = "`uname -r`"; then depmod -a ; fi
+	@getent group oprofile >/dev/null || (echo "Error: The special group 'oprofile' does not exist" && exit 1) ;
+	@getent passwd oprofile >/dev/null || (echo "Error: The special user 'oprofile' does not exist" && exit 1) ;
+	@if test `id -gn oprofile 2>/dev/null` != "oprofile"; then \
+		echo "Error: The special user 'oprofile' does not belong to the special group 'oprofile'."; \
+		exit 1; \
+	fi
 
 clean-local:
 	rm -f module/*.o module/@OPROFILE_MODULE_ARCH@/*.o \
 	module/.*.o.cmd module/.*.o.flags \
 	module/@OPROFILE_MODULE_ARCH@/.*.o.cmd module/@OPROFILE_MODULE_ARCH@/.*.o.flags
+
+else
+
+install-exec-local:
+	@getent group oprofile >/dev/null || (echo "Error: The special group 'oprofile' does not exist" && exit 1) ;
+	@getent passwd oprofile >/dev/null || (echo "Error: The special user 'oprofile' does not exist" && exit 1) ;
+	@if test `id -gn oprofile 2>/dev/null` != "oprofile"; then \
+		echo "Error: The special user 'oprofile' does not belong to the special group 'oprofile'."; \
+		exit 1; \
+	fi
 
 endif
 
