oprof_start silently failed if a counter is missing, nmi watchdog up for example, we must check for this in opcontrol and exit 1 if something is wrong, at the same time we can provide valuable advise on how to work around this in recent kernel

diff --git a/utils/opcontrol b/utils/opcontrol
--- a/utils/opcontrol
+++ b/utils/opcontrol
@@ -1044,7 +1044,17 @@ set_ctr_param()
 	fi
 
 	if test "$KERNEL_SUPPORT" = "yes"; then
-		echo $3 >$MOUNT/$1/$2
+		if test -e $MOUNT/$1; then
+			echo $3 >$MOUNT/$1/$2
+		else
+			echo -n "Error: counter $1 not available"
+			if test -e /proc/sys/kernel/nmi_watchdog; then
+				echo " nmi_watchdog using this resource ? Try:"
+				echo "opcontrol --deinit"
+				echo "echo 0 > /proc/sys/kernel/nmi_watchdog"
+			fi
+			exit 1
+		fi
 	else
 		$SYSCTL -w dev.oprofile.$1.$2=$3
 	fi
