disallow --rtc-value when needed

diff --git a/utils/opcontrol b/utils/opcontrol
--- a/utils/opcontrol
+++ b/utils/opcontrol
@@ -505,6 +505,11 @@ do_options() {
 					;;
 			esac
 		fi
+
+		if test "$CPU_TYPE" != "5" -a "$arg" = "--rtc-value"; then
+			echo "Cannot use --rtc-value; RTC driver is not being used" >& 2
+			exit 1
+		fi
  
 		case "$arg" in
 
